### ISSUE TITLE
Make distance file output more deterministic

### ISSUE THREAD

**Issue by stevenweaver** [veg/tn93#1]
Currently, the output of the CSV file outputs with unsorted edges, we should print the output sorted by the first column. 

To reproduce: 
Run tn93 twice, save the output, and notice the differences between files. 

We need to have sorted rows in order for some testing environments to work.

**Comment by spond** [comment]
This behavior **should** only occur during multithreaded execution. Sorting would be expensive and unnecessary, plus you would have to sort by first AND second column, and there's no guarantee that the names are unique (that could lead to unstable sort behavior).

For testing, I would recommend adding a flag to specify that OpenMP should be disabled.
