### ISSUE TITLE
fasta_diff.cpp Error on Install 

### ISSUE THREAD

**Issue by jwertheim** [veg/tn93#15]
Installation failure on MacOS 10.14.4 upon "cmake ." command. Errors and warnings reference fasta_diff.cpp  (see output below).

Cheers,
Joel

Tanyas-iMac-Pro:tn93 WertheimLab$ sudo cmake .
-- The C compiler identification is AppleClang 10.0.1.10010046
-- The CXX compiler identification is AppleClang 10.0.1.10010046
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Could NOT find OpenMP_C (missing: OpenMP_C_FLAGS OpenMP_C_LIB_NAMES) 
-- Could NOT find OpenMP_CXX (missing: OpenMP_CXX_FLAGS OpenMP_CXX_LIB_NAMES) 
-- Could NOT find OpenMP (missing: OpenMP_C_FOUND OpenMP_CXX_FOUND) 
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/WertheimLab/tn93
Tanyas-iMac-Pro:tn93 WertheimLab$ sudo make install
Scanning dependencies of target validate_fasta
[  2%] Building CXX object CMakeFiles/validate_fasta.dir/src/validate_fasta.cpp.o
[  4%] Building CXX object CMakeFiles/validate_fasta.dir/src/stringBuffer.cc.o
[  7%] Building CXX object CMakeFiles/validate_fasta.dir/src/tn93_shared.cc.o
[  9%] Linking CXX executable validate_fasta
[  9%] Built target validate_fasta
Scanning dependencies of target selectreads
[ 11%] Building CXX object CMakeFiles/selectreads.dir/src/trim_reads.cpp.o
[ 14%] Building CXX object CMakeFiles/selectreads.dir/src/stringBuffer.cc.o
[ 16%] Building CXX object CMakeFiles/selectreads.dir/src/tn93_shared.cc.o
[ 19%] Building CXX object CMakeFiles/selectreads.dir/src/argparse_trim.cpp.o
[ 21%] Linking CXX executable selectreads
[ 21%] Built target selectreads
Scanning dependencies of target ShortestPathTN93
[ 23%] Building CXX object CMakeFiles/ShortestPathTN93.dir/src/ShortestPathTN93.cpp.o
[ 26%] Building CXX object CMakeFiles/ShortestPathTN93.dir/src/stringBuffer.cc.o
[ 28%] Building CXX object CMakeFiles/ShortestPathTN93.dir/src/tn93_shared.cc.o
[ 30%] Linking CXX executable ShortestPathTN93
[ 30%] Built target ShortestPathTN93
Scanning dependencies of target tn93
[ 33%] Building CXX object CMakeFiles/tn93.dir/src/TN93.cpp.o
[ 35%] Building CXX object CMakeFiles/tn93.dir/src/stringBuffer.cc.o
[ 38%] Building CXX object CMakeFiles/tn93.dir/src/tn93_shared.cc.o
[ 40%] Building CXX object CMakeFiles/tn93.dir/src/argparse.cpp.o
[ 42%] Linking CXX executable tn93
[ 42%] Built target tn93
Scanning dependencies of target nucfreqsfasta
[ 45%] Building CXX object CMakeFiles/nucfreqsfasta.dir/src/nuc_freqs_from_fasta.cpp.o
[ 47%] Building CXX object CMakeFiles/nucfreqsfasta.dir/src/stringBuffer.cc.o
[ 50%] Building CXX object CMakeFiles/nucfreqsfasta.dir/src/tn93_shared.cc.o
[ 52%] Linking CXX executable nucfreqsfasta
[ 52%] Built target nucfreqsfasta
Scanning dependencies of target readreduce
[ 54%] Building CXX object CMakeFiles/readreduce.dir/src/read_reducer.cpp.o
[ 57%] Building CXX object CMakeFiles/readreduce.dir/src/stringBuffer.cc.o
[ 59%] Building CXX object CMakeFiles/readreduce.dir/src/tn93_shared.cc.o
[ 61%] Building CXX object CMakeFiles/readreduce.dir/src/argparse_merge.cpp.o
[ 64%] Linking CXX executable readreduce
[ 64%] Built target readreduce
Scanning dependencies of target seqcoverage
[ 66%] Building CXX object CMakeFiles/seqcoverage.dir/src/charfreqs.cpp.o
[ 69%] Building CXX object CMakeFiles/seqcoverage.dir/src/stringBuffer.cc.o
[ 71%] Building CXX object CMakeFiles/seqcoverage.dir/src/tn93_shared.cc.o
[ 73%] Building CXX object CMakeFiles/seqcoverage.dir/src/argparse_cf.cpp.o
[ 76%] Linking CXX executable seqcoverage
[ 76%] Built target seqcoverage
Scanning dependencies of target fasta_diff
[ 78%] Building CXX object CMakeFiles/fasta_diff.dir/src/fasta_diff.cpp.o
/Users/WertheimLab/tn93/src/fasta_diff.cpp:37:9: warning: 'auto' type specifier is a C++11 extension [-Wc++11-extensions]
        auto compare_records = [&] (const std::string & id1, const char* seq_value) -> int {
        ^
/Users/WertheimLab/tn93/src/fasta_diff.cpp:37:32: error: expected expression
        auto compare_records = [&] (const std::string & id1, const char* seq_value) -> int {
                               ^
/Users/WertheimLab/tn93/src/fasta_diff.cpp:85:9: warning: 'auto' type specifier is a C++11 extension [-Wc++11-extensions]
        auto echo_fasta_sequence = [&] (const char* id, const char* data, FILE * where) -> void {
        ^
/Users/WertheimLab/tn93/src/fasta_diff.cpp:85:36: error: expected expression
        auto echo_fasta_sequence = [&] (const char* id, const char* data, FILE * where) -> void {
                                   ^
/Users/WertheimLab/tn93/src/fasta_diff.cpp:105:17: warning: 'auto' type specifier is a C++11 extension [-Wc++11-extensions]
                auto it = sequences_to_add.find (master_id);
                ^
/Users/WertheimLab/tn93/src/fasta_diff.cpp:156:57: warning: range-based for loop is a C++11 extension [-Wc++11-extensions]
            for (std::pair<std::string, std::string> it : sequences_to_add) {
                                                        ^
/Users/WertheimLab/tn93/src/fasta_diff.cpp:171:32: warning: range-based for loop is a C++11 extension [-Wc++11-extensions]
            for (std::string s : updated_sequences) {
                               ^
5 warnings and 2 errors generated.
make[2]: *** [CMakeFiles/fasta_diff.dir/src/fasta_diff.cpp.o] Error 1
make[1]: *** [CMakeFiles/fasta_diff.dir/all] Error 2
make: *** [all] Error 2

**Comment by spond** [comment]
Dear @jwertheim,

Fixed with 77fc406d18e484266c41cbaf01887fcc56c3eaa3

Best,
Sergei

**Comment by jwertheim** [comment]
Thanks Sergei! Installation works now.

Cheers,
Joel
