### ISSUE TITLE
Handle commas in sequence IDs?

### ISSUE THREAD

**Issue by niemasd** [veg/tn93#28]
Hey, folks! I recently tried computing pairwise distances from a SARS-CoV-2 MSA that included the reference genome (which has a comma in the FASTA sequence ID), and this breaks the `tn93` CSV output. Here's a minimal reproducible example:

```
>Species X, complete genome
ACGTACGTAC
>Species Y, complete genome
ACGTACGTAA
>Species Z, complete genome
CCGTACGTAC
```

The `tn93` CSV output is as follows:

```
ID1,ID2,Distance
Species X, complete genome,Species Y, complete genome,0.108711
Species Y, complete genome,Species Z, complete genome,0.239924
Species X, complete genome,Species Z, complete genome,0.108711
```

As a quick workaround, I'm just removing commas from my input FASTA, but would it be possible to add support for commas in sequence IDs within `tn93`? Some potential ideas:
* The simplest solution might be to allow the user to use tabs to delimit columns instead of commas (e.g. as a `--tsv-output` flag?)
  * Or perhaps let the user specify an arbitrary delimiter? (e.g. as a `--delimiter ?` flag?)
* A less simple solution would be to wrap comma-containing IDs in quotes, e.g.:
  * `"Species X, complete genome","Species Y, complete genome",0.108711`

No pressure/rush, and I totally understand just requiring the user to not have commas in the IDs, but just a proposition 😄

**Comment by spond** [comment]
Dear @niemasd,

Added the `-D` options in v1.0.10

Best,
Sergei

**Comment by niemasd** [comment]
Thanks so much for the quick patch, @spond!
