### ISSUE TITLE
error with CXXABI_1.3.8

### ISSUE THREAD

**Issue by vagnerfonseca** [veg/tn93#6]
I'm facing the following error with other server users.
`tn93: /usr/lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by tn93)`
but for me it worked add to the environment
```
LD_LIBRARY_PATH=/usr/local/lib64/:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH
```

but for other users this is not working.

```
strings /usr/local/lib64/libstdc++.so | grep CXXABI
CXXABI_1.3
CXXABI_1.3.1
CXXABI_1.3.2
CXXABI_1.3.3
CXXABI_1.3.4
CXXABI_1.3.5
CXXABI_1.3.6
CXXABI_1.3.7
CXXABI_1.3.8
CXXABI_1.3.9
CXXABI_1.3.10
CXXABI_TM_1
CXXABI_FLOAT128
```
```
strings /usr/lib64/libstdc++.so.6 | grep CXXABI
CXXABI_1.3
CXXABI_1.3.1
CXXABI_1.3.2
CXXABI_1.3.3

```

**Comment by stevenweaver** [comment]
Dear @vagnerfonseca, 

It looks as though you may be setting the `LD_LIBRARY_PATH` incorrectly. The path you are setting in LD_LIBRARY PATH is not `/usr/lib64`. 

Please try
```
export LD_LIBRARY_PATH=/usr/lib64/:$LD_LIBRARY_PATH
```

**Comment by vagnerfonseca** [comment]
tn93 is using `/usr/lib64/` instead it should use `/usr/local/lib64/`

**Comment by stevenweaver** [comment]
Dear @vagnerfonseca, 

Apologies, you are correct. 

Do other users have executable permission to `/usr/local/lib64` (e.g. can they type the command `ls /usr/local/lib64/` and see that they get results?

Have you ensured that the symlink `/usr/local/lib64/libstdc++.so.6` exists and that it points to the same library that `/usr/local/lib64/libstdc++.so` points to?

Best,
Steven

**Comment by vagnerfonseca** [comment]
Do other users have executable permission to /usr/local/lib64 (e.g. can they type the command ls /usr/local/lib64/ and see that they get results?
**YES**

Have you ensured that the symlink /usr/local/lib64/libstdc++.so.6 exists and that it points to the same library that /usr/local/lib64/libstdc++.so points to?
**YES**

**Comment by vagnerfonseca** [comment]
Hi @stevenweaver,

I fix the problem enabling `scl` for all users

thank you!
